version: '3.8'

services:
  # Backend service (API and core logic)
  nofx:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.backend
    container_name: nofx-trading
    restart: unless-stopped
    ports:
      - "${NOFX_BACKEND_PORT:-8080}:8080"
    volumes:
      - ./config.json:/app/config.json:ro
      # 可选：挂载外部配置文件到其他路径，然后通过 command 覆盖
      # - /path/to/your/config.json:/app/custom-config.json:ro
      - ./decision_logs:/app/decision_logs
      - /etc/localtime:/etc/localtime:ro  # Sync host time
    environment:
      - TZ=${NOFX_TIMEZONE:-Asia/Shanghai}  # Set timezone
    # 可选：使用自定义配置文件路径（取消注释并修改路径）
    # command: ['./nofx', '/app/custom-config.json']
    networks:
      - nofx-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Frontend service (static serving and proxy)
  nofx-frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.frontend
    container_name: nofx-frontend
    restart: unless-stopped
    ports:
      - "${NOFX_FRONTEND_PORT:-3000}:80"
    networks:
      - nofx-network
    depends_on:
      - nofx
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

networks:
  nofx-network:
    driver: bridge